<?php

namespace App\Presenters;

use Nette;
use App\Model;


class HomepagePresenter extends BasePresenter
{

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }

    public function renderDefault()
  	{
  	}

    public function actionTransition()
    {
      # code...
    }

    public function actionInvolved()
    {
      # code...
    }

}
