<?php

namespace App\Presenters;

use Nette;
use App\Model;


class ResearchPresenter extends BasePresenter
{

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }

    public function renderDefault($research_id)
  	{
  	}

    public function actionTeam($research_id)
    {
    }

    public function actionActions($research_id)
    {
    }

    public function actionChangeInformation($research_id)
    {
    }

    public function actionEdit($research_id)
    {
      # code...
    }

}
